version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-52-86-73-86.compute-1.amazonaws.com
            database: dc3rneoju0l04t
            schema: public
            user: vvfbovxbjbfxec
            password: 596585c31b49d2c5bccc1a80af63a7095c76a56d0107d1c1e988eb376ae3128a
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true